INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('4226', '排水户过期信息导出', '4214', '8', '#', NULL, 'F', '0', 'drainage:expire:export', '#', 'admin', TO_DATE('2019-10-27 10:54:26', 'SYYYY-MM-DD HH24:MI:SS'), 'admin', TO_DATE('2019-10-27 10:54:29', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL);


INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6130', '人员信息导出', '6100', '33', '#', NULL, 'F', '0', 'employee:worker:export', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL);
INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6131', '水厂信息导出', '6100', '34', '#', NULL, 'F', '0', 'employee:factory:export', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL);



