
--  2020.5.18修改
DROP TABLE "RY"."DM_COST";
DROP SEQUENCE SEQ_DM_COST;

CREATE TABLE "RY"."DM_COST" (
"COST_ID" NUMBER(20) NOT NULL ,
"COST_FACTORY" VARCHAR2(100 BYTE) NULL ,
"COST_COMPANY" VARCHAR2(100 BYTE) NULL ,
"COST_APPLY_TIME" DATE NULL ,
"COST_PAY_TIME" VARCHAR2(30 BYTE) NULL ,
"COST_WATER_VOLUME" NUMBER(20) NULL ,
"COST_PAY_MONEY" NUMBER(20) NULL ,
"COST_PUNISH_MONEY" NUMBER(20) NULL ,
"COST_PUNISH_REASON" VARCHAR2(255 BYTE) NULL ,
"COST_REMARK" VARCHAR2(255 BYTE) NULL ,
"COST_FILE_NAME" VARCHAR2(255 BYTE) NULL ,
"COST_FILE_PATH" VARCHAR2(255 BYTE) NULL ,
"CREATE_TIME" DATE NULL 
)
LOGGING
NOCOMPRESS
NOCACHE;


COMMENT ON COLUMN "RY"."DM_COST"."COST_FACTORY" IS '水质净化厂';
COMMENT ON COLUMN "RY"."DM_COST"."COST_COMPANY" IS '运营单位';
COMMENT ON COLUMN "RY"."DM_COST"."COST_APPLY_TIME" IS '申请支付时间';
COMMENT ON COLUMN "RY"."DM_COST"."COST_PAY_TIME" IS '实际支付时间';
COMMENT ON COLUMN "RY"."DM_COST"."COST_WATER_VOLUME" IS '实际处理水量';
COMMENT ON COLUMN "RY"."DM_COST"."COST_PAY_MONEY" IS '实付处理费';
COMMENT ON COLUMN "RY"."DM_COST"."COST_PUNISH_MONEY" IS '处罚金额';
COMMENT ON COLUMN "RY"."DM_COST"."COST_PUNISH_REASON" IS '处罚原因';
COMMENT ON COLUMN "RY"."DM_COST"."COST_REMARK" IS '备注';
COMMENT ON COLUMN "RY"."DM_COST"."COST_FILE_NAME" IS '文件名';
COMMENT ON COLUMN "RY"."DM_COST"."COST_FILE_PATH" IS '文件相对路径';
COMMENT ON COLUMN "RY"."DM_COST"."CREATE_TIME" IS '创建时间';

-- ----------------------------
-- Indexes structure for table DM_COST
-- ----------------------------

-- ----------------------------
-- Checks structure for table DM_COST
-- ----------------------------
ALTER TABLE "RY"."DM_COST" ADD CHECK ("COST_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table DM_COST
-- ----------------------------
ALTER TABLE "RY"."DM_COST" ADD PRIMARY KEY ("COST_ID");

CREATE SEQUENCE SEQ_DM_COST  
increment by 1    -- 每次递增1  
start with 1       -- 从1开始  
nomaxvalue      -- 没有最大值  
minvalue 1       -- 最小值=1  
NOCYCLE;      -- 不循环

