INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6101', '人员信息查看', '6100', '25', '/employee/worker', 'menuItem', 'C', '1', 'employee:worker:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, 'op');
INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6105', '水厂信息查看', '6100', '26', '/employee/factory', 'menuItem', 'C', '1', 'employee:factory:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, 'op');
INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6107', '公司信息查看', '6100', '27', '/employee/company', 'menuItem', 'C', '1', 'employee:company:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, 'op');
INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6118', '部门信息查看', '6100', '28', '/employee/department', 'menuItem', 'C', '1', 'employee:department:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, 'op');


INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6126', '排水户信息查看', '4214', '29', '/drainage/household', 'menuItem', 'C', '1', 'drainage:household:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, 'op');
INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6127', '排水户数据统计信息查看', '4214', '30', '/drainage/statistics/statistics', 'menuItem', 'C', '1', 'drainage:statistics:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, 'op');
INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6128', '排水户过期信息查看', '4214', '31', '/drainage/expire', 'menuItem', 'C', '1', 'drainage:expire:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, 'op');
INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6129', '地图服务信息查看', '4214', '32', '#', 'menuItem', 'C', '1', 'drainage:maphousehold:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, 'op');
