INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6101', '人员信息查看', '6100', '25', '#', NULL, 'F', '0', 'employee:worker:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL);

INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6105', '水厂信息查看', '6100', '26', '#', NULL, 'F', '0', 'employee:factory:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL);

INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6107', '公司信息查看', '6100', '27', '#', NULL, 'F', '0', 'employee:company:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL);

INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6118', '部门信息查看', '6100', '28', '#', NULL, 'F', '0', 'employee:department:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL);




INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6126', '排水户信息查看', '6100', '29', '#', NULL, 'F', '0', 'drainage:household:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL);

INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6127', '排水户数据统计信息查看', '6100', '30', '#', NULL, 'F', '0', 'drainage:statistics:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL);

INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6128', '排水户过期信息查看', '6100', '31', '#', NULL, 'F', '0', 'drainage:expire:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL);

INSERT INTO "RY"."SYS_MENU" ("MENU_ID", "MENU_NAME", "PARENT_ID", "ORDER_NUM", "URL", "TARGET", "MENU_TYPE", "VISIBLE", "PERMS", "ICON", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME", "REMARK", "SUBSYS_FLAG") VALUES ('6129', '地图服务信息查看', '6100', '32', '#', NULL, 'F', '0', 'drainage:maphousehold:view', '#', 'admin', TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2019-09-16 11:33:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL);





